#ifndef GMEM_TYPES_H_
#define GMEM_TYPES_H_

#include <stdio.h>

typedef enum gmem_status {
    GMEM_SUCCESS,
    GMEM_ERROR_CODE_NONE,
    GMEM_ERROR_CODE_INVALID_ARGUMENTS,
    GMEM_ERROR_NO_DEVICE,
    GMEM_ERROR_NO_MEMORY,
    GMEM_ERROR_CODE_OUT_OF_MEMORY,
    GMEM_ERROR_CODE_NOT_IMPLEMENTED,
    GMEM_ERROR_CODE_INTERNAL_ERROR,
    GMEM_ERROR_CODE_LAST
} gmem_status_t;

#endif /* GMEM_TYPES_H_ */